export const categories = [
  {
    dir: 'export',
    num: '01',
    nameStart: 'Agricultural ',
    nameEm: 'Commodities',
    tagline: "Nigeria's harvest, professionally sourced and exported to global food, beverage, and ingredient markets.",
    items: [
      { name: 'Gum Arabic', desc: 'Grades A1 & A2. Food, pharma, cosmetics.' },
      { name: 'Sesame Seeds', desc: 'White and mixed. Bakery, tahini, oils.' },
      { name: 'Cashew Nuts (RCN)', desc: 'Raw cashew, container loads.' },
      { name: 'Soya Beans', desc: 'Non-GMO. Oil extraction, animal feed.' },
      { name: 'Hibiscus (Zobo)', desc: 'Dried calyces. Beverage, colour, wellness.' },
      { name: 'Shea Butter & Nuts', desc: 'Cosmetics, food, pharmaceutical industry.' },
      { name: 'Tiger Nuts', desc: 'Health food market. EU and Americas.' },
      { name: 'Cocoa & Cocoa Products', desc: 'Beans and semi-processed. EU chocolatiers.' },
      { name: 'Palm Oil (Crude)', desc: 'CPO for food and industrial use.' },
      { name: 'Groundnuts', desc: 'Raw and processed. Oil and food markets.' },
      { name: 'Moringa Products', desc: 'Leaves, powder, seeds. Wellness sector.' },
      { name: 'Ginger & Turmeric', desc: 'Premium spice and food applications.' },
      { name: 'Pepper (Chilli / Black)', desc: 'Sun-dried, processed. Spice markets.' },
      { name: 'Crayfish & Seafood', desc: 'Dried. Diaspora and African food importers.' },
      { name: 'Hardwood Charcoal', desc: 'Premium BBQ. EU retail and grilling brands.' },
    ],
  },
  {
    dir: 'export',
    num: '02',
    nameStart: 'Solid ',
    nameEm: 'Minerals & Natural Resources',
    tagline: 'Industrial minerals from licensed Nigerian sources, exported through fully regulated international channels.',
    items: [
      { name: 'Gold', desc: 'Licensed channels to international refineries.' },
      { name: 'Limestone', desc: 'High-grade. Cement and construction.' },
      { name: 'Coal', desc: 'Thermal and coking. Power and steel.' },
      { name: 'Zinc Ore', desc: 'Concentrate for global smelters.' },
      { name: 'Lead Ore', desc: 'Concentrate for industrial processors.' },
      { name: 'Iron Ore', desc: 'For Asian steel mills.' },
      { name: 'Baryte', desc: 'For global oil drilling operations.' },
      { name: 'Kaolin (Clay)', desc: 'Paper, ceramics, rubber industries.' },
      { name: 'Feldspar', desc: 'Glass and ceramics manufacturing.' },
      { name: 'Talc', desc: 'Cosmetics, paper, plastics.' },
      { name: 'Manganese Ore', desc: 'For global steel alloy producers.' },
      { name: 'Granite', desc: 'Dimension stone for construction.' },
    ],
  },
  {
    dir: 'export',
    num: '03',
    nameStart: 'Petrochemicals & ',
    nameEm: 'Energy Products',
    tagline: 'Crude, refined fuels, gas, and petrochemicals — traded through verified international counterparties.',
    items: [
      { name: 'Crude Oil (Bonny Light)', desc: "Nigeria's flagship grade." },
      { name: 'Refined Products', desc: 'PMS, AGO, DPK where licensed.' },
      { name: 'LPG', desc: 'West African regional markets.' },
      { name: 'LNG', desc: 'NLNG-linked off-take support.' },
      { name: 'Bitumen', desc: 'Natural and synthetic. Construction.' },
      { name: 'Petrochemical Feedstock', desc: 'Ethylene, propylene, derivatives.' },
    ],
  },
  {
    dir: 'export',
    num: '04',
    nameStart: 'Processed & ',
    nameEm: 'Manufactured Goods',
    tagline: 'Value-added Nigerian production — for diaspora markets, global industry, and lifestyle retail worldwide.',
    items: [
      { name: 'Processed Foods & Beverages', desc: 'Diaspora markets in UK, US, EU, Canada, Middle East.' },
      { name: 'Leather & Hides', desc: 'Raw and semi-processed. Global tanneries.' },
      { name: 'Cotton & Textiles', desc: 'Lint and fabrics. Asian and EU manufacturers.' },
      { name: 'Rubber (Natural)', desc: 'Tyre and industrial rubber processors.' },
      { name: 'Wood & Timber', desc: 'Legally sourced. Construction and furniture.' },
      { name: 'Pharmaceutical APIs', desc: 'Active ingredients, regulatory compliant.' },
      { name: 'Artisan & Craft', desc: 'Handmade Nigerian goods. Lifestyle markets.' },
    ],
  },
  {
    dir: 'import',
    num: '05',
    nameStart: 'Machinery, Equipment & ',
    nameEm: 'Industrial Goods',
    tagline: 'Industrial infrastructure for Nigerian agriculture, construction, energy, healthcare, and manufacturing.',
    items: [
      { name: 'Agricultural Machinery', desc: 'Tractors, harvesters, irrigation systems.' },
      { name: 'Construction Equipment', desc: 'Excavators, mixers, cranes, generators.' },
      { name: 'Power & Energy Equipment', desc: 'Solar, inverters, transformers.' },
      { name: 'Medical Equipment', desc: 'Hospital and diagnostic devices.' },
      { name: 'Industrial Machinery', desc: 'Food, textile, cement processing.' },
      { name: 'Mining & Drilling', desc: 'Minerals extraction and oil & gas.' },
    ],
  },
  {
    dir: 'import',
    num: '06',
    nameStart: 'Consumer Goods & ',
    nameEm: 'FMCG',
    tagline: 'Daily-use products and consumer essentials sourced from global manufacturers for the Nigerian retail market.',
    items: [
      { name: 'Electronics & Appliances', desc: 'Phones, laptops, home appliances.' },
      { name: 'Clothing & Footwear', desc: 'Branded and generic apparel.' },
      { name: 'Food & Beverages', desc: 'Wheat, rice, sugar, oils, dairy.' },
      { name: 'Personal & Household Care', desc: 'Toiletries, cleaning, cosmetics.' },
      { name: 'Furniture & Furnishings', desc: 'Premium residential and commercial.' },
      { name: 'Vehicles & Spare Parts', desc: 'New and used. Consumer and commercial.' },
      { name: 'Toys & Sporting Goods', desc: 'Retail and e-commerce.' },
    ],
  },
  {
    dir: 'import',
    num: '07',
    nameStart: 'Raw Materials for ',
    nameEm: 'Local Industries',
    tagline: 'Industrial inputs that keep Nigerian factories, farms, and manufacturing running every single day.',
    items: [
      { name: 'Industrial Chemicals', desc: 'Caustic soda, acids, solvents, dyes.' },
      { name: 'Steel & Iron Products', desc: 'Billets, bars, rods, sheets.' },
      { name: 'Aluminium & Non-Ferrous Metals', desc: 'Packaging, construction, engineering.' },
      { name: 'Paper & Packaging', desc: 'Cartons, reels, industrial packaging.' },
      { name: 'Plastics & Polymers', desc: 'PET, HDPE, polypropylene.' },
      { name: 'Pharma Raw Materials', desc: 'APIs and excipients for local pharma.' },
      { name: 'Fertilisers & Agrochemicals', desc: 'NPK, urea, herbicides, pesticides.' },
      { name: 'Textile Raw Materials', desc: 'Cotton yarn, fibres, industrial fabrics.' },
    ],
  },
];

export const exportCorridors = [
  { country: 'United States', products: 'Gum Arabic · Hibiscus · Sesame · Cocoa · Shea Butter · Niche Foods' },
  { country: 'European Union', products: 'Charcoal · Cocoa · Sesame · Gum Arabic · Leather · Minerals' },
  { country: 'China · India · Japan', products: 'Sesame · Cashew · Rubber · Coal · Iron Ore · Zinc' },
  { country: 'Middle East (UAE · Saudi Arabia)', products: 'Gum Arabic · Sesame · Foodstuffs · Minerals' },
  { country: 'ECOWAS Region (West Africa)', products: 'Processed foods · Petroleum products · Agro commodities' },
];

export const importCorridors = [
  { country: 'China · India', products: 'Electronics · Machinery · Chemicals · Steel · Textiles' },
  { country: 'European Union (Germany · Netherlands · Italy)', products: 'Machinery · Pharmaceuticals · Food · Vehicles · Industrial Goods' },
  { country: 'United States & Canada', products: 'Agricultural Equipment · Medical Devices · Consumer Goods' },
  { country: 'United Kingdom', products: 'Machinery · Specialty Chemicals · Premium FMCG' },
  { country: 'Turkey · UAE · Brazil', products: 'Textiles · Steel · Construction Materials · Foodstuffs' },
];

export const promises = [
  { num: '01', title: 'Sourced at origin', text: "We buy directly from licensed exporters and cooperative networks in Nigeria's primary production states. No middlemen. No mystery." },
  { num: '02', title: 'Tested and certified', text: 'Every container is inspected by SGS, Bureau Veritas, or Cotecna before it leaves Nigeria. Moisture, aflatoxin, anthocyanin, residue. The numbers are real.' },
  { num: '03', title: 'Documented end to end', text: 'NEPC NXP, phytosanitary, NAFDAC where required, EU Common Health Entry Documents on arrival. Nothing missing. Nothing improvised.' },
  { num: '04', title: 'Handled internally', text: 'Our sister company, Romana Clearance Limited, handles port operations at Apapa and Tin Can. The supply chain stays inside the group.' },
  { num: '05', title: 'Paid through structure', text: 'Letters of Credit, advance payment, or structured offtake agreements. We protect the buyer. We protect the seller. We protect the trade.' },
];

export const processSteps = [
  { num: '01', title: 'Source', text: 'Engage Tier 1 exporters and verified aggregators in producing states. Confirm volume, grade, and price.' },
  { num: '02', title: 'Inspect', text: 'Independent quality testing before shipment. Certified lab results travel with every container.' },
  { num: '03', title: 'Ship', text: 'Customs clearance through Romana Clearance at Apapa. Ocean freight to Europe, Asia, or the Americas.' },
  { num: '04', title: 'Deliver', text: 'EU import clearance, final delivery, buyer inspection, payment release. The cycle closes cleanly.' },
];
